[package]
name = "mecab-wrapper"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = ["cmecab"]
cmecab = ["libc"]


[dependencies]
libc = { version = "0.2", optional = true }
csv = { version = "1.2" }

[build-dependencies]
cc = { version = "1.0" }
